name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t net-tracer-builder -f docker/Dockerfile.build .

    - name: Build project
      run: |
        mkdir -p output
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -v ${{ github.workspace }}/output:/workspace/output \
          net-tracer-builder

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: net-tracer-binaries
        path: |
          output/**/*
        if-no-files-found: error
